### ISSUE TITLE
Unexpected error occurred: GenericArguments[0]

### ISSUE THREAD

**Issue by keif888** [keif888/SQLServerMetadata#19]
This issue is split from Issue #17 
The error below occurred when trying to scan a SSIS 2017 Catalog.
Enumerating Integration Services metadata.
Unexpected error occurred: GenericArguments[0], 'Microsoft.SqlServer.Management.IntegrationServices.Catalog', on 'Microsoft.SqlServer.Management.Sdk.Sfc.SfcCollection`3[T,K,ParentT]' violates the constraint of type parameter 'T'.
Stack Trace:
at Microsoft.Samples.DependencyAnalyzer.SSISEnumerator.EnumerateSqlPackages(String server, String user, String pwd, String[] rootFolders, Boolean storeThreePartNames, String[] storePackagePasswords)
at Microsoft.Samples.DependencyAnalyzer.Program.EnumerateSSIS(DependencyArguments dependencyArguments, Repository repository)
at Microsoft.Samples.DependencyAnalyzer.Program.Main(String[] args)

**Comment by keif888** [comment]
Fixed in V0.25.0.0 release.
Issue was due to lack of required DLL on client machines (as MS are no longer deploying it as part of the SSDT's installs), and missing .config file for the 2017 analyser.
