### ISSUE TITLE
Reading package from SSISDB fails

### ISSUE THREAD

**Issue by keif888** [keif888/SQLServerMetadata#8]
Hi,

I am trying to read packages from the SSISDB, as I am using project connection managers most packages fail. However the dependency analyzer does not even scan all packages.

I have the following:

Error enumerating packages on SQL Server 'hostname123': Could not find a part of the path 'C:\Users\fmoeller\AppData\Local\Temp\3\SSISMDaf87bdd9-ae00-47e6-b85d-d53c358e1b8a\DWH.ZIP'.
Strack Trace :   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at Microsoft.Samples.DependencyAnalyzer.SSISEnumerator.EnumerateProjectPackages(ProjectInfo project, DirectoryInfo tempDirectory, String server)
   at Microsoft.Samples.DependencyAnalyzer.SSISEnumerator.EnumerateSqlPackages(String server, String user, String pwd, String[] rootFolders, Boolean storeThreePartNames, String[] storePackagePasswords)
Committing analysis information to database...Completed.
Looking in the Temp folder I can see that the ZIP archive is created however disappears after just a few seconds.

I'd be willing to test any updates.

regards and thanks
Felix

**Comment by keif888** [comment]
fmoeller wrote Jul 29, 2016 at 5:56 AM 
I guess the mistake is introduced with commit112034 

https://sqlmetadata.codeplex.com/SourceControl/changeset/112034
wrote Jan 10 at 11:16 PM

**Comment by fmms** [comment]
It was me creating the original Codeplex Bug. In January 2017, somebody else commented at https://sqlmetadata.codeplex.com/SourceControl/changeset/112034 that removing that one line solves this problem ...

**Comment by keif888** [comment]
Release 20 now on Github has this fix applied.
(sorry for the delay, but I've been unable to compile the solution due to an issue with MSAGL and VS2017.  https://github.com/Microsoft/automatic-graph-layout/issues/111)

**Comment by fmms** [comment]
thank you very much. I have just verified this issue is solved with Release 20.
